// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/layout', 'controllers/session_controller', 'controllers/navigation_controller', 'controllers/sidebar_controller', 'routes'], function(Chaplin, Layout, SessionController, NavigationController, SidebarController, routes) {
  'use strict';

  var FacebookApplication;
  return FacebookApplication = (function(_super) {

    __extends(FacebookApplication, _super);

    function FacebookApplication() {
      return FacebookApplication.__super__.constructor.apply(this, arguments);
    }

    FacebookApplication.prototype.title = 'Chaplin Example Application with Facebook login';

    FacebookApplication.prototype.initialize = function() {
      FacebookApplication.__super__.initialize.apply(this, arguments);
      this.initDispatcher();
      this.initLayout();
      this.initMediator();
      this.initControllers();
      this.initRouter(routes);
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    FacebookApplication.prototype.initLayout = function() {
      return this.layout = new Layout({
        title: this.title
      });
    };

    FacebookApplication.prototype.initControllers = function() {
      new SessionController();
      new NavigationController();
      return new SidebarController();
    };

    FacebookApplication.prototype.initMediator = function() {
      Chaplin.mediator.user = null;
      return Chaplin.mediator.seal();
    };

    return FacebookApplication;

  })(Chaplin.Application);
});
